api:
  commands:
    forget:
      confirmation_required: true
      enabled: true
    recall:
      enabled: true
      similarity_threshold: 0.85
    remember:
      enabled: true
      max_items: 25
bcm:
  attention_heads: 2
  decay_rate: 0.98
  embedding_dim: 256
  memory_size: 64
  salience_threshold: 0.9
  update_gate_type: gru
device:
  compile_model: false
  mixed_precision: false
  preferred: cpu
execution_engine:
  async_execution: false
  cpu_threads: 8
  max_concurrent_modules: 2
  memory_budget_gb: 8
  offload_threshold: 0.7
  priority_scheduling: true
igpm:
  fast_weight_decay: 0.995
  instruction_embedding_dim: 64
  max_episodic_memories: 100
  meta_learning_rate: 0.001
  plastic_slots: 8
  plasticity_threshold: 0.9
inference:
  max_new_tokens: 256
  max_sequence_length: 4096
  repetition_penalty: 1.05
  temperature: 0.8
  top_k: 30
  top_p: 0.85
logging:
  level: INFO
  log_file: core_nn_laptop_optimized.log
  log_inference_time: true
  log_memory_usage: true
  tensorboard_dir: runs_laptop_optimized
memory:
  episodic_memory_size: 256
  memory_consolidation_interval: 25
  semantic_memory_size: 1024
  working_memory_size: 128
mlcs:
  auto_compress_threshold: 0.9
  codebook_size: 2048
  compression_ratio: 0.1
  kpack_max_size_mb: 10
  latent_dim: 64
  num_compression_levels: 2
model:
  name: core-nn-laptop-aggressively-optimized
  version: 0.2.2
rteu:
  activation: gelu
  capsule_dim: 16
  dropout: 0.1
  embedding_dim: 256
  hidden_dim: 512
  num_capsules: 4
  num_layers: 2
  routing_iterations: 1
  temporal_scales:
  - 1
  - 2
  - 4
session:
  auto_save: true
  max_session_history: 3
  save_interval: 300
  session_dir: sessions_optimized
tokenizer:
  custom_config_path: null
  overrides:
    cache_size: 2500
    enable_contextual_merging: true
    max_sequence_length: 2048
  preset: edge
  type: asc
training:
  batch_size: 1
  gradient_clipping: 0.25
  learning_rate: 0.0001
  max_steps: 25000
  warmup_steps: 250
  weight_decay: 0.01
